# -*- coding: utf-8 -*-
"""bucket_sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C-saMaXHoZWSXwJNGeeEayEhhuLdZwoi
"""

# Implementación de bucket sort
# Javier Figueroa Estrada

def bucketSort(array):
    cubeta = []

    # Creamos tantas cubetas vacías como la longitud del arreglo
    for i in range(len(array)):
        cubeta.append([])

    # Insertamos los elementos en su respectiva cubeta
    for j in array:
        index_b = int(j / 10)#formato de entero
        cubeta[index_b].append(j)

    # Ordenamos los elementos de cada cubeta con el método sorted
    for i in range(len(array)):
        cubeta[i] = sorted(cubeta[i])

    # Obtenemos todos los elementos de las cubetas
    k = 0
    for i in range(len(array)):
        for j in range(len(cubeta[i])):
            array[k] = cubeta[i][j]
            k += 1
    return array


array = [ 56, 35, 33, 52, 17, 47, 51]
print("El array en orden es")
print(bucketSort(array))