# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lyUOVTVEKqKO_j6DZFP9ate3zIlIHZp3
"""

#DAA 1511
#Javier Figueroa Estrada
alfabeto = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ"
cifrado = "Si Cupdmzaplil Uikpwuis Icbwuwti lm Tmfpkw oi lmamtxmvilw cu xixms xzwbiñwupkw mu si opabwzpi g mu si nwztikpwu lm ucmabzw xipa. Sia bizmia acabiubpdia lm mabi puabpbckpwu xcjspki, icbwuwti g sipki awu si lwkmukpi, si pudmabpñikpwu g si lpncapwu lm si kcsbczi. Mu ms tculw ikilmtpkw ma zmkwuwkpli kwtw cui cupdmzaplil lm mfkmsmukpi. Si CUIT zmaxwulm is xzmamubm g tpzi ms ncbczw kwtw ms xzwgmkbw kcsbczis tia ptxwzbiubm lm Tmfpkw.Si CUIT ma cu maxikpw lm spjmzbilma. Mu mssi am xzikbpki kwbplpiuitmubm ms zmaxmbw, si bwsmziukpi g ms lpiswñw. Si xsczisplil lm plmia g lm xmuaitpmubw ma ixzmkpili kwtw apñuw lm ac zpycmhi g ucuki kwtw nikbwz lm lmjpsplil"

for clave in range(1,27): # no ponemos 0 porque sería el mismo mensaje"
    mensaje = ""

    for letra in cifrado.upper():#volvemos todo mayúsculas el mensaje
        if letra in alfabeto:
            indice = alfabeto.find(letra)
            indice -= clave #restamos la clave para recorrer el índice
            if indice < 0:
                indice += 27 # si el ínidice es menor a 0, le sumamos 27 para empezar por el final
            mensaje += alfabeto[indice]
        else:
            mensaje += letra

        print(f"Clave {clave}:  {mensaje} ")
#La clave es 8